### ISSUE TITLE
Refine documentation

### ISSUE THREAD

**Issue by AlvinHon** [parallelchain-io/pchain-client-rust#1]
Here is to suggest updates on the documentation.

1. The readme states the current version os 0.4.2, but the latest one os 0.4.3

2. in error.rs, the heading comment uses "//!", "///!" and "///" which is kind of mess up.

3. also in same file, block comment on function use double slash which is rarely used in rust style comment. Suggest to change to "///".

**Comment by TLiu2084** [comment]
The documentation updates will be pushed together with protocol v0.5 changes.
